version: '3.8'

services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: c_nginx
    ports:
      - "8080:80"
    volumes:
      - ./phone:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
    networks:
      - phoneList

  php-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: c_php
    ports:
      - "9000:9000"
    volumes:
      - ./phone:/var/www/project
    networks:
      - phoneList

  mysql-service:
    image: mysql:8.0.33
    container_name: c_mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_app:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - "3306:3306"
    networks:
      - phoneList

volumes:
  db_app:

networks:
  phoneList:
    driver: bridge